/**
 * Dictionnaire des libellés d'interface (FR / EN / DE / AR).
 * Usage : `const T = ui[lang] || ui.FR;` dans les composants.
 * Les contenus longs par section (Hero, Studio, Contact, Art) vivent dans
 * leurs propres composants ; ici : navigation, boutons, en-têtes, page projet,
 * libellés du curseur personnalisé, cartels du viewer 3D et titres de document.
 *
 * ⚠️ Toute clé ajoutée ici DOIT l'être dans les QUATRE langues : l'arabe ne
 * doit jamais retomber sur le français (exigence de traduction intégrale).
 */
export const ui = {
  FR: {
    nav: { index: 'Index', projets: 'Projets', studio: 'Studio', contact: 'Contact' },
    menu: {
      open: 'Menu',
      close: 'Fermer',
      sections: 'Sections',
      home: 'Accueil',
      projets: 'Projets',
      art: 'Art & Expérimentation',
      skills: 'Logiciels',
      contact: 'Contact',
      architecture: 'Architecture',
      catArt: 'Art & Expérimentation',
    },
    projects: { tag: '(Projets sélectionnés)', index: 'Index — 05', sommaire: 'Sommaire' },
    feature: { cta: 'Voir le projet →' },
    project: {
      back: '← Index',
      label: 'Projet',
      model: 'Maquette 3D',
      scene: 'Scène 3D',
      docs: 'Documents & images',
      realized: 'Projet réalisé',
      next: 'Projet suivant',
      prev: 'Projet précédent',
      // Titres de chapitre génériques, répartis sur les paragraphes de l'article
      // (voir `buildChapters` dans projects.js).
      quoteMarks: ['« ', ' »'],
      chIntention: 'Intention',
      chProjet: 'Le projet',
      chMatiere: 'Matière & détail',
      // Modale plein écran (voir ui/Lightbox.jsx).
      lightbox: {
        title: 'Visionneuse',
        close: 'Fermer',
        prev: 'Image précédente',
        next: 'Image suivante',
      },
    },
    skills: 'Logiciels',
    notFound: { text: "Cette page n'existe pas", home: "Retour à l'accueil" },
    // Libellés du curseur personnalisé (voir layout/CustomCursor.jsx).
    cursor: {
      discover: 'Découvrir',
      view: 'Voir',
      go: 'Aller',
      next: 'Suivant',
      write: 'Écrire',
      open: 'Ouvrir',
      look: 'Regarder',
      turn: 'Tourner',
      prev: 'Précédent',
    },
    viewer: {
      unavailable: 'Modèle indisponible',
      hintLook: 'Glisser pour regarder · 360°',
      hintTurn: 'Glisser pour tourner',
    },
    doc: {
      title: 'Dana Adib — Architecture',
      description: "Dana Adib — portfolio d'architecture. Espaces, matière et récit.",
      notFound: 'Page introuvable',
    },
  },
  EN: {
    nav: { index: 'Index', projets: 'Projects', studio: 'Studio', contact: 'Contact' },
    menu: {
      open: 'Menu',
      close: 'Close',
      sections: 'Sections',
      home: 'Home',
      projets: 'Projects',
      art: 'Art & Experiments',
      skills: 'Software',
      contact: 'Contact',
      architecture: 'Architecture',
      catArt: 'Art & Experiments',
    },
    projects: { tag: '(Selected projects)', index: 'Index — 05', sommaire: 'Contents' },
    feature: { cta: 'View project →' },
    project: {
      back: '← Index',
      label: 'Project',
      model: '3D model',
      scene: '3D scene',
      docs: 'Documents & images',
      realized: 'Built project',
      next: 'Next project',
      prev: 'Previous project',
      quoteMarks: ['“', '”'],
      chIntention: 'Intention',
      chProjet: 'The project',
      chMatiere: 'Material & detail',
      lightbox: {
        title: 'Viewer',
        close: 'Close',
        prev: 'Previous image',
        next: 'Next image',
      },
    },
    skills: 'Software',
    notFound: { text: "This page doesn't exist", home: 'Back to home' },
    cursor: {
      discover: 'Discover',
      view: 'View',
      go: 'Go',
      next: 'Next',
      write: 'Write',
      open: 'Open',
      look: 'Look',
      turn: 'Turn',
      prev: 'Previous',
    },
    viewer: {
      unavailable: 'Model unavailable',
      hintLook: 'Drag to look around · 360°',
      hintTurn: 'Drag to rotate',
    },
    doc: {
      title: 'Dana Adib — Architecture',
      description: 'Dana Adib — architecture portfolio. Space, material and narrative.',
      notFound: 'Page not found',
    },
  },
  DE: {
    nav: { index: 'Index', projets: 'Projekte', studio: 'Studio', contact: 'Kontakt' },
    menu: {
      open: 'Menü',
      close: 'Schließen',
      sections: 'Bereiche',
      home: 'Startseite',
      projets: 'Projekte',
      art: 'Kunst & Experimente',
      skills: 'Software',
      contact: 'Kontakt',
      architecture: 'Architektur',
      catArt: 'Kunst & Experimente',
    },
    projects: { tag: '(Ausgewählte Projekte)', index: 'Index — 05', sommaire: 'Inhalt' },
    feature: { cta: 'Projekt ansehen →' },
    project: {
      back: '← Index',
      label: 'Projekt',
      model: '3D-Modell',
      scene: '3D-Szene',
      docs: 'Dokumente & Bilder',
      realized: 'Realisiertes Projekt',
      next: 'Nächstes Projekt',
      prev: 'Vorheriges Projekt',
      quoteMarks: ['„', '“'],
      chIntention: 'Intention',
      chProjet: 'Das Projekt',
      chMatiere: 'Material & Detail',
      lightbox: {
        title: 'Betrachter',
        close: 'Schließen',
        prev: 'Vorheriges Bild',
        next: 'Nächstes Bild',
      },
    },
    skills: 'Software',
    notFound: { text: 'Diese Seite existiert nicht', home: 'Zurück zur Startseite' },
    cursor: {
      discover: 'Entdecken',
      view: 'Ansehen',
      go: 'Los',
      next: 'Weiter',
      write: 'Schreiben',
      open: 'Öffnen',
      look: 'Umsehen',
      turn: 'Drehen',
      prev: 'Zurück',
    },
    viewer: {
      unavailable: 'Modell nicht verfügbar',
      hintLook: 'Ziehen zum Umsehen · 360°',
      hintTurn: 'Ziehen zum Drehen',
    },
    doc: {
      title: 'Dana Adib — Architektur',
      description: 'Dana Adib — Architektur-Portfolio. Raum, Material und Erzählung.',
      notFound: 'Seite nicht gefunden',
    },
  },
  AR: {
    nav: { index: 'الفهرس', projets: 'المشاريع', studio: 'استوديو', contact: 'تواصل' },
    menu: {
      open: 'القائمة',
      close: 'إغلاق',
      sections: 'الأقسام',
      home: 'الرئيسية',
      projets: 'المشاريع',
      art: 'فنّ وتجريب',
      skills: 'البرامج',
      contact: 'تواصل',
      architecture: 'عمارة',
      catArt: 'فنّ وتجريب',
    },
    projects: { tag: '(مشاريع مختارة)', index: 'الفهرس — 05', sommaire: 'الفهرس' },
    feature: { cta: '← عرض المشروع' },
    project: {
      back: 'الفهرس →',
      label: 'مشروع',
      model: 'مجسّم ثلاثي الأبعاد',
      scene: 'مشهد ثلاثي الأبعاد',
      docs: 'مستندات وصور',
      realized: 'مشروع مُنجَز',
      next: 'المشروع التالي',
      prev: 'المشروع السابق',
      quoteMarks: ['«', '»'],
      chIntention: 'النيّة',
      chProjet: 'المشروع',
      chMatiere: 'المادة والتفصيل',
      lightbox: {
        title: 'العارض',
        close: 'إغلاق',
        prev: 'الصورة السابقة',
        next: 'الصورة التالية',
      },
    },
    skills: 'البرامج',
    notFound: { text: 'هذه الصفحة غير موجودة', home: 'العودة إلى الرئيسية' },
    cursor: {
      discover: 'اكتشف',
      view: 'شاهد',
      go: 'انتقل',
      next: 'التالي',
      write: 'راسل',
      open: 'افتح',
      look: 'انظر حولك',
      turn: 'أدر',
      prev: 'السابق',
    },
    viewer: {
      unavailable: 'المجسّم غير متاح',
      hintLook: 'اسحب للنظر حولك · 360°',
      hintTurn: 'اسحب للتدوير',
    },
    doc: {
      title: 'دانا أديب — عمارة',
      description: 'دانا أديب — بورتفوليو عمارة. فضاء ومادة وسرد.',
      notFound: 'الصفحة غير موجودة',
    },
  },
};

export default ui;
